# Generated by Django 4.1.2 on 2023-01-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('que', models.CharField(max_length=20)),
                ('anw', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='static/uploaded_images')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.user_data')),
            ],
        ),
    ]
