# Generated by Django 4.1.2 on 2023-01-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_notice_alter_complaint_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('action', models.BooleanField()),
                ('fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.user_data')),
            ],
        ),
    ]
