# Generated by Django 4.1.2 on 2023-01-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_appointment_action_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='anw',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='que',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='', upload_to='static/assets/uploaded_images'),
        ),
    ]
