# Generated by Django 4.1.2 on 2023-02-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_user_data_anw_remove_user_data_que_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='adhar',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
