# Generated by Django 4.1.2 on 2023-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_data_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(default='', upload_to='static/assets/uploaded_images'),
        ),
    ]
