# Generated by Django 4.1.2 on 2023-03-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action',
            field=models.BooleanField(null=True),
        ),
    ]
